### ISSUE TITLE
Should we read the disk on every page fault?

### ISSUE THREAD

**Issue by elliott-beach** [elliott-beach/project2_base#11]
The current code: https://github.com/elliott-beach/project2_base/blob/6086fc7fe51df1c1ff13e40e7f3abdce38a161c3/main.c#L52-L59
does a disk read every time we assign a page to a frame.
We should only need to do this when the page was already _assigned_ to a frame, and then unassigned and reassigned again. 

The assignment wants us to graph disk reads as well as page faults, signaling that we should not read from the disk every time.

**Comment by elliott-beach** [comment]
We could add a data structure to have a bit for each page on whether it has been used yet.
@kstowe do you agree with this?

**Comment by ghost** [comment]
I'm not sure what you mean 
> We should only need to do this when the page was already assigned to a frame, and then unassigned and reassigned again
>
I think this might have to do with the dirty bit though. We haven't implemented it yet.  Every time we load a page in from disk, we should set permissions to `PROT_READ` only with no write permissions. 

This would explain why we aren't getting any page faults on write operations.

**Comment by elliott-beach** [comment]
We fixed it somewhere.
