### ISSUE TITLE
Random Segfaults on FIFO Paging

### ISSUE THREAD

**Issue by elliott-beach** [elliott-beach/project2_base#12]
Running `make experiment` turns up segfaults every so often on the fifo paging. Awkward...

```
⋊> ~/C/5/project2_base on metrics ⨯ make experiment                                                                                                                               09:24:27
reads writes faults
program: sort
rand
1027 1017 1027 
772  752  772  
548  508  548  
250  170  250  
100  0    100  
fifo
935  925  935  
683  673  683  
478  468  478  
disk_write: invalid block #32560
Aborted (core dumped)
disk_write: invalid block #32636
Aborted (core dumped)
program: scan
rand
1100 1090 1100 
1094 1074 1094 
1005 965  1005 
482  402  482  
100  0    100  
fifo
1100 1090 1100 
1100 1090 1100 
1100 1090 1100 
1100 1090 1100 
101  91   101  
program: focus
rand
295  285  295  
273  253  273  
242  202  242  
157  77   157  
100  0    100  
fifo
288  278  288  
275  265  275  
247  237  247  
200  190  200  
101  91   101  
⋊> ~/C/5/project2_
```
/cc @kstowe

**Comment by ghost** [comment]
Does that happen for you every time? It doesn't seem to be happening on my machine at all.

**Comment by elliott-beach** [comment]
Not every time.
Segfaults are machine and execution dependent, so that’s not a big surprise.
You are using my `metrics` PR to test, I assume?

**Comment by ghost** [comment]
Yes

**Comment by elliott-beach** [comment]
07c15bc fixed this as far as I can tell.
What was happening is that the loop at line 40 was executing without a hit sometimes, leaving `frame` uninitialized. Then `loadFrameIntoPage` would be called with frame initialized randomly.
https://github.com/elliott-beach/project2_base/blob/1fbbabd253328b2b4f8649f7a174abda8e93c236/main.c#L37-L42

**Comment by ghost** [comment]
What did you change to fix it?  How could that loop execute without initializing frame first?

**Comment by elliott-beach** [comment]
If you click on 07c15bc that’s a link to the commit where I changed stuff.

The loop executed all the way through because the frame is assigned to no page, because the initial assignment loop stopped at 10 when it should stop at `nframes`. So `if ... page_mapping[curr_page] == frame ...` never gets a hit.

Stopping at 10 was just an oversight.
